### ISSUE TITLE
Dashboard texture does not appear

### ISSUE THREAD

**Issue by GamersCave** [BenoitDuffez/crashreportsviewer#12]
There is no dashboard texture. It just says "No data yet" and no texture. Did I misunderstand with the dashboard texture or does it appear when tehre are errors to show?

**Comment by Polarbear0106** [comment]
Probably solved. YOu should specify this backend requires PHP 7.0. Updated it but cannot know for another 30 minutes

**Comment by BenoitDuffez** [comment]
Thanks for your find. I'll update the readme.

**Comment by GamersCave** [comment]
actually, I'm not sure anymore
I upgraded to PHP 7 but that requires mysqli which requires rewriting of everything. The paths are wrong. in install.php the .htaccess changed is the primary one for my website, not for the viewer. PHP 7 doesn't support MySQL and everything has to be upgraded to MySQLi. I'm sorry about the confusion, but PHP 7 cannot be used because it removes ALL MySQL and it has to be upgraded to MySQLi. The paths are wring. With .../config.php my system cannot find it. I had to create my own backend and it is still not perfect.

**Comment by BenoitDuffez** [comment]
Anyway this project is very old, rusty, the code base is not pretty and I don't have time to maintain it.
I have personnaly switched to fabric.io.
I'd gladly accept pull requests, but I don't have time to investigate any issue.

**Comment by GamersCave** [comment]
WHen I set this up I had to edit lots of paths. There are so many path-based issues so eventually after lots of struggling with the setup, I just made my own. But thank you for making this. People like me who doesn't have CouchDB really needs this.
